import { Exchange, type ExchangeMeta } from '../types/exchange.js';

export const EXCHANGES: ExchangeMeta[] = [
  {
    code: Exchange.MCX,
    name: 'MCX',
    fullName: 'Multi Commodity Exchange of India',
    country: 'India',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    website: 'https://www.mcxindia.com',
    sessions: [{
      exchange: Exchange.MCX,
      name: 'Regular',
      timezone: 'Asia/Kolkata',
      openTime: '09:00',
      closeTime: '23:30',
      tradingDays: [1, 2, 3, 4, 5],
    }],
  },
  {
    code: Exchange.NCDEX,
    name: 'NCDEX',
    fullName: 'National Commodity & Derivatives Exchange',
    country: 'India',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    website: 'https://www.ncdex.com',
    sessions: [{
      exchange: Exchange.NCDEX,
      name: 'Regular',
      timezone: 'Asia/Kolkata',
      openTime: '09:00',
      closeTime: '17:00',
      tradingDays: [1, 2, 3, 4, 5],
    }],
  },
  {
    code: Exchange.CME,
    name: 'CME',
    fullName: 'Chicago Mercantile Exchange',
    country: 'USA',
    timezone: 'America/Chicago',
    currency: 'USD',
    website: 'https://www.cmegroup.com',
    sessions: [{
      exchange: Exchange.CME,
      name: 'Globex',
      timezone: 'America/Chicago',
      openTime: '17:00',
      closeTime: '16:00',
      tradingDays: [0, 1, 2, 3, 4],
    }],
  },
  {
    code: Exchange.COMEX,
    name: 'COMEX',
    fullName: 'Commodity Exchange Inc',
    country: 'USA',
    timezone: 'America/New_York',
    currency: 'USD',
    website: 'https://www.cmegroup.com',
    sessions: [{
      exchange: Exchange.COMEX,
      name: 'Globex',
      timezone: 'America/New_York',
      openTime: '18:00',
      closeTime: '17:00',
      tradingDays: [0, 1, 2, 3, 4],
    }],
  },
  {
    code: Exchange.NYMEX,
    name: 'NYMEX',
    fullName: 'New York Mercantile Exchange',
    country: 'USA',
    timezone: 'America/New_York',
    currency: 'USD',
    website: 'https://www.cmegroup.com',
    sessions: [{
      exchange: Exchange.NYMEX,
      name: 'Globex',
      timezone: 'America/New_York',
      openTime: '18:00',
      closeTime: '17:00',
      tradingDays: [0, 1, 2, 3, 4],
    }],
  },
  {
    code: Exchange.CBOT,
    name: 'CBOT',
    fullName: 'Chicago Board of Trade',
    country: 'USA',
    timezone: 'America/Chicago',
    currency: 'USD',
    website: 'https://www.cmegroup.com',
    sessions: [{
      exchange: Exchange.CBOT,
      name: 'Globex',
      timezone: 'America/Chicago',
      openTime: '19:00',
      closeTime: '13:20',
      tradingDays: [0, 1, 2, 3, 4],
    }],
  },
  {
    code: Exchange.LME,
    name: 'LME',
    fullName: 'London Metal Exchange',
    country: 'UK',
    timezone: 'Europe/London',
    currency: 'USD',
    website: 'https://www.lme.com',
    sessions: [{
      exchange: Exchange.LME,
      name: 'Ring',
      timezone: 'Europe/London',
      openTime: '01:00',
      closeTime: '19:00',
      tradingDays: [1, 2, 3, 4, 5],
    }],
  },
  {
    code: Exchange.ICE,
    name: 'ICE',
    fullName: 'Intercontinental Exchange',
    country: 'USA',
    timezone: 'America/New_York',
    currency: 'USD',
    website: 'https://www.ice.com',
    sessions: [{
      exchange: Exchange.ICE,
      name: 'Electronic',
      timezone: 'America/New_York',
      openTime: '20:00',
      closeTime: '18:00',
      tradingDays: [0, 1, 2, 3, 4],
    }],
  },
  {
    code: Exchange.ICE_EU,
    name: 'ICE EU',
    fullName: 'Intercontinental Exchange Europe',
    country: 'UK',
    timezone: 'Europe/London',
    currency: 'USD',
    website: 'https://www.ice.com',
    sessions: [{
      exchange: Exchange.ICE_EU,
      name: 'Electronic',
      timezone: 'Europe/London',
      openTime: '01:00',
      closeTime: '19:00',
      tradingDays: [1, 2, 3, 4, 5],
    }],
  },
];

export const EXCHANGE_BY_CODE = new Map(EXCHANGES.map(e => [e.code, e]));
